### ISSUE TITLE
【Feature Request】识别中英语言并自动选择语音引擎

### ISSUE THREAD

**Issue by cyio** [u14app/gemini-next-chat#18]
互联网用户很多同时使用中英两种语音与 AI 对话，目前的语音朗读只能手动切换，希望根据 AI 输出内容所属语言（大致判断），自动使用对应的语音角色。

**Comment by Amery2010** [comment]
According to current tests, most Chinese voices support bilingual pronunciation in Chinese and English, without the need to switch voice types.
