### ISSUE TITLE
[Feature Request]: 失去焦点隐藏

### ISSUE THREAD

**Issue by rebron1900** [u14app/gemini-next-chat#35]
### Problem Description

现在要点了图标才会显示/隐藏

### Solution Description

希望可以设置成失去焦点后隐藏。

**Comment by Amery2010** [comment]
之前试过失去焦点隐藏页面，但在某些场景下（比如mac 多屏幕状态经常会被其他 App 抢占焦点以至于意外隐藏），这个功能为会想一下如何兼顾多种场景，需要后续版本才会更新。

**Comment by rebron1900** [comment]
另外，刚安装的时候不知道该如何以悬浮窗口显示，还以为是单独运行程序后才可以用，后来通过右键缩小后缺又打不开主窗口，测试了几次才发现使用方法，可以在文档里说明一下。
