### ISSUE TITLE
[Feature Request]: 自定义助理

### ISSUE THREAD

**Issue by keethebest** [u14app/gemini-next-chat#42]
### Problem Description

目前没办法自己建立一个助理

### Solution Description

希望能支持自定义助理的功能

**Comment by Amery2010** [comment]
已经在需求列表中了，不过需要再等两个版本，目前正在开发类似 GPTs 插件功能，无法同步开发其他功能。

**Comment by Amery2010** [comment]
The new version already supports custom assistants
