### ISSUE TITLE
当我在对话框输入标准格式的代码时，实际显示长度超出界面范围

### ISSUE THREAD

**Issue by player868** [u14app/gemini-next-chat#48]
这是显示bug的图片，希望作者能够修复显示问题。
![Screenshot_20240811_213850](https://github.com/user-attachments/assets/567eed26-a26a-4de3-9e37-eec5f316d812)

**Comment by Amery2010** [comment]
了解了，之前没有测试这种场景下的文本溢出，后续版本中会做修复
