### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by 1487879421888** [u14app/gemini-next-chat#50]
### Problem Description

大佬，下个版本什么时候出来呢?

### Solution Description

大佬，下个版本什么时候出来呢?

### Additional Context

大佬，下个版本什么时候出来呢?

**Comment by Amery2010** [comment]
这段时间比较忙，一直没时间开发，大概停止开发了 1个月，下个版本是一个大版本更新，会具备插件功能（Function Call），预计9月中旬左右发布

**Comment by Amery2010** [comment]
A new major version has been updated, which includes plugins, custom assistants and conversation list
![pc-screenshot-3](https://github.com/user-attachments/assets/2338f580-dd07-4fe1-ada0-0434264eb52b)
