### ISSUE TITLE
[Feature Request]: 希望通过环境变量能内置全局提示词

### ISSUE THREAD

**Issue by bestZwei** [u14app/gemini-next-chat#56]
### Problem Description

希望通过环境变量能内置全局提示词

### Solution Description

希望通过环境变量能内置全局提示词

**Comment by Amery2010** [comment]
该功能会在下一个大版本里同步更新，新版本目前还在内测中，预计 12月中旬之前发布。

**Comment by Amery2010** [comment]
Currently supports custom assistant function, the content set by the assistant is the system prompt
