### ISSUE TITLE
当文件上传后，对话框布局显示出现了问题

### ISSUE THREAD

**Issue by player532** [u14app/gemini-next-chat#57]
如图：
![Screenshot_20241207_211253](https://github.com/user-attachments/assets/7d36d11b-a627-4bd8-9878-64d207c61073)
![Screenshot_20241207_210826](https://github.com/user-attachments/assets/df822b5c-723f-4e4c-99c5-b3c973c0934b)

**Comment by Amery2010** [comment]
I have received feedback and will fix it in the near future.

**Comment by Amery2010** [comment]
I have fixed these typographical issues, thank you for your feedback
