### ISSUE TITLE
模型列表中，有许多模型名出现重复现象，请求作者矫正实际模型名

### ISSUE THREAD

**Issue by player532** [u14app/gemini-next-chat#61]
![Screenshot_20241210_080742](https://github.com/user-attachments/assets/7c519125-47a2-4577-9e22-aa479c19476d)

**Comment by Amery2010** [comment]
Thanks for the feedback, but this is not an error, it is the result returned by Gemini API. During the test, I found that in the returned model list, different names of models have the same displayName. This is also the reason why the exp-1206 model could not be found when the displayName was used to filter the model.

I will consider optimizing the display of the model.

**Comment by player532** [comment]
作者，这样修改的名字太长了，移动端上的模型名不仅显得眼花缭乱，长度还超出了显示范围，不易辨识。作者可以想个办法解决一下吗？求求了！🙏🙏
![Screenshot_20241212_143303](https://github.com/user-attachments/assets/c8b085db-4185-46f3-81c4-f20137bfd82c)

**Comment by Amery2010** [comment]
These models are not caused by code logic errors, but the model names returned by the official API are repeated. If I follow the names, some models will be lost. For example, you will not be able to get exp-1206 normally because there are multiple model names pointing to Gemini Experimental 1206
Please refer to the model number after the model name.
I believe Google will fix the problem of duplicate model list names in the near future

**Comment by player532** [comment]
虽然我知道这不是错误，但我还是想要请求你，把正常获取的模型名一律复原回原来的名称，只保留其它无法正常获取的模型名（就是你主动修改过后的模型名。）虽然这很麻烦，但是移动端上显示是超出了一定范围的，查看模型名非常的不方便。求求了！我并不强求你这么做，一切都是出于你的决定与选择。

**Comment by player532** [comment]
另外作者能够看一下，模型被选中时，蓝色下划线为什么是空的吗？感谢作者！
![IMG_20241214_123802](https://github.com/user-attachments/assets/5745bb4e-3371-4539-8dbd-38d990c32340)

**Comment by Amery2010** [comment]
> 另外作者能够看一下，模型被选中时，蓝色下划线部分为什么是空着的吗？感谢作者！ ![IMG_20241214_123802](https://private-user-images.githubusercontent.com/190836111/395743688-5745bb4e-3371-4539-8dbd-38d990c32340.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNTc4MzUsIm5iZiI6MTczNDE1NzUzNSwicGF0aCI6Ii8xOTA4MzYxMTEvMzk1NzQzNjg4LTU3NDViYjRlLTMzNzEtNDUzOS04ZGJkLTM4ZDk5MGMzMjM0MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQwNjI1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYThhYzgwMTJmNTk1OTgyYTJjMWNlODY5OWYxOWJlZGM0NTI0MTg3ZTA2YmRkNTlkZjMyMzEyYjgxOTM2ZWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ArJBEIihRb6KSVU2cVUhkuQQykKKPcurt4BdmMzhIEM)

It may be a style problem caused by other model names being too long. I will fix it later.
