### ISSUE TITLE
[Bug] Error message when using Web-Search

### ISSUE THREAD

**Issue by A1Marky** [u14app/gemini-next-chat#64]
### Bug Description

I'm currently using the webapp and I keep getting **500: DDG detected an anomaly in the request, you are likely making requests too quickly.** while using the Official "Web-search" plugin. I tried with and without an assistant activated and had "Web Reader" and "Web Search" activated. Small prompt and gave it 15 minutes tried again and was still getting the error.

### Steps to Reproduce

1. https://gemini.u14.app/
2. Web Search | Web Reader Official Plugin turned on
3. API Key set
4. Gave it a prompt to search the web for app ideas using browser tool

### Expected Behavior

I expected to see the web search sources and have the return of the details.

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows 10

### Desktop Browser

Microsoft Edge

### Desktop Browser Version

Latest

**Comment by laorent** [comment]
Hello, my deployment to the Vercel container is complete, but why can't I use the plugin? Every time I try, it shows a 500 error. However, it works fine on your GitHub site.

**Comment by Amery2010** [comment]
> Hello, my deployment to the Vercel container is complete, but why can't I use the plugin? Every time I try, it shows a 500 error. However, it works fine on your GitHub site.

I will try to fix it, but in the short term the service will be affected by the ip throttling of the DDG service.
