### ISSUE TITLE
代码块无法正常显示出来，请求作者解决

### ISSUE THREAD

**Issue by player532** [u14app/gemini-next-chat#66]
模型使用的是Gemini-2.0-flash-thinking-exp，当我要求它写代码时，由于“```”紧挨着其它字符，结果就显示成了这样，无法形成代码块。作者能看看到底是什么问题吗？
![Screenshot_2024_1220_150802](https://github.com/user-attachments/assets/9d07810d-a255-44d3-80c8-6cc5538cc1a9)

**Comment by Amery2010** [comment]
gemini-2.0-flash-thinking-exp This model has a thinking process, which is fixed as a special English explanation. I need to study whether there are specific symbols in this fixed text to distinguish it from the main text.

**Comment by player532** [comment]
> gemini-2.0-flash-thinking-exp This model has a thinking process, which is fixed as a special English explanation. I need to study whether there are specific symbols in this fixed text to distinguish it from the main text.

所以目前是否有办法能够解决代码块形成异常的问题？或者说，是否有临时解决的方法？我只想恳求作者尽快解决此问题🙏🙏

**Comment by player532** [comment]
@Amery2010 作者，我有个更好的想法。不妨先把像这样Gemini 2.0 flash thinking exp这样具备思考能力模型，就是说把思考过程输出先给忽略掉，仅输出最终输出结果，待到issue #68 所描述的功能实现后，再把思考过程输出加入，作者觉得如何？因为在目前来看，思考过程输出并不是很重要的一项。

**Comment by Amery2010** [comment]
I have located and fixed a problem with code blocks rendering when the code language type is missing.
Will be updated in the next minor version

**Comment by Amery2010** [comment]
I fixed this issue
