### ISSUE TITLE
[Bug] The project deployed via Vercel cannot use plugins

### ISSUE THREAD

**Issue by laorent** [u14app/gemini-next-chat#67]
### Bug Description

The project deployed via Vercel cannot use plugins and displays a 500: Token is invalid error code and the model being used is Gemini 1.5 Flash latest, and the same issue occurs with all other models as well.

### Steps to Reproduce

"1. Click on the website to enter.
2. Click on the desired plugin.
3. Ask a question.
4. An error message '500: Token is invalid' appears, and sometimes the response is irrelevant to the question."

### Expected Behavior

It is expected that after the developer clicks, the plugin can be used.

### Screenshots

![image](https://github.com/user-attachments/assets/ab3634c1-fc2a-48a0-80ac-498ebe077851)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

windows11

### Desktop Browser

edge and Chrome

### Smartphone Device

Android

### Smartphone OS

12

### Smartphone Browser

edge and brave

**Comment by laorent** [comment]
> `Token is invalid` means that the access password you entered is incorrect. You can try to re-enter the correct access password. If your backend service does not set an access password, please make sure that the access password in the settings is empty. `Token is invalid`
"The password is correct. I have tried it before and can communicate with the large model."

**Comment by Amery2010** [comment]
The plugin functionality has been refactored and is no longer called from the server
