### ISSUE TITLE
一个小小的建议：作者可以实现此功能吗？

### ISSUE THREAD

**Issue by player532** [u14app/gemini-next-chat#68]
我的想法是这样的，像Gemini 2.0 flash thinking exp这样的模型，是具备思考能力的，虽然目前还是实验性的模型，但是如果可以把思考过程与最终输出分离开就更好了，这样就不会轻易混淆输出，并且非常直观的辨别出来模型想法。就像图下所示一样，使用模型想法面板明晰的展示出来思考过程。如果这是可以被实现的，那么请求作者实现：
![Screenshot_20241220_223223](https://github.com/user-attachments/assets/d4e303c1-cdb8-4ce7-8c39-edd79eadd827)

**Comment by Amery2010** [comment]
I will implement this feature in subsequent development.

**Comment by Amery2010** [comment]
Implemented
