### ISSUE TITLE
模型选择列表无法正常显示，求作者解决

### ISSUE THREAD

**Issue by player532** [u14app/gemini-next-chat#71]
当我在选择模型时，模型选择列表部分被遮挡，并显示异常，就像这样，求作者解决，或者恳求改善布局位置。这已经是模型选择列表的最底部：
![Screenshot_20241231_114207](https://github.com/user-attachments/assets/e0c0bf32-8b7f-4b54-bbba-cd6180a2ce16)

**Comment by player532** [comment]
从桌面端ua来看，它已经在移动端上显示明显溢出了
![Screenshot_20241231_114840](https://github.com/user-attachments/assets/e04fbde9-9b7d-4ff2-b957-22ec255c0472)

**Comment by Amery2010** [comment]
I have fixed it

**Comment by player532** [comment]
> I have fixed it

@Amery2010 模型列表中，许多的模型版本都离奇消失了，无法使用这些更新的模型，作者能看看吗？

https://github.com/user-attachments/assets/fe7d6e99-6d73-401f-b3df-98a83be09652

**Comment by player532** [comment]
> > I have fixed it
> 
> @Amery2010 模型列表中，许多的模型版本都离奇消失了，导致大部分模型无法使用，作者能看看吗？
> 
> 原站点：https://gemini.u14.app/
> 
>  Screenrecording_20241231_125432.mp4

@Amery2010 经测试，如果浏览器的数据被清除，重新打开该网站，就会复现视频中模型缺失的情况。不过，我是在应用程序中清除数据的。如果仅仅刷新网页，则不会触发该bug，求作者解决。

**Comment by player532** [comment]
@Amery2010 语言列表似乎也同样出现了遮挡的现象
![Screenshot_20241231_131924](https://github.com/user-attachments/assets/78290159-8e0a-4313-9dd8-fdba3f4e9e1c)

**Comment by Amery2010** [comment]
Adaptation for small-screen mobile phones is more difficult. I will consider this issue, but it will not be implemented in the near future.

**Comment by player532** [comment]
> > I have fixed it
> 
> [@Amery2010](https://github.com/Amery2010) 模型列表中，许多的模型版本都离奇消失了，导致大部分模型无法使用，作者能看看吗？
> 
> 原站点：https://gemini.u14.app/
> 
>  Screenrecording_20241231_125432.mp4

@Amery2010 该错误在
https://gemini.u14.app/
1.5.3版本再次出现，请求作者修复

**Comment by Amery2010** [comment]
Long lists are not very user-friendly for small-screen devices, and there is currently no good solution.

**Comment by player532** [comment]
> Long lists are not very user-friendly for small-screen devices, and there is currently no good solution.

@Amery2010 这并非是ui显示方面不兼容的问题，只是说大多数模型又像之前一样离奇消失，导致无法使用更先进的大多数模型，具体情况请看我上句话所引用的问题描述

**Comment by Amery2010** [comment]
I have fixed the problem that the model list cannot be obtained normally in the scenario without access password
